import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import style from './layout.module.css';
import {MovieData} from "@/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Footer() {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_API_SERVER_URL}/movie`,
    {cache: 'force-cache'}
  );

  if (!response.ok) {
    return <div>오류가 발생했습니다...</div>
  }

  const movies: MovieData[] = await response.json();

  return (
    <div style={{color: '#FFFFFF', paddingTop: '20px'}}>
      <footer>
        제작 @bitnalchan92
      </footer>
      총 {movies.length}건의 영화가 등록되어 있습니다.
    </div>
  )
}

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <div className={style.container}>
      <header>
        <Link href="/">ONEBITE CINEMA</Link>
      </header>
      <main>{children}</main>
      <Footer/>
    </div>
    </body>
    </html>
  );
}
